/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseErrMsg: typeof import('./components/share/BaseErrMsg.vue')['default']
    BaseForm: typeof import('./components/share/BaseForm.vue')['default']
    BaseInput: typeof import('./components/share/BaseInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./components/Test.vue')['default']
  }
}
